---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gov-w3l1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gov-w3l1
  template:
    metadata:
      labels:
        app: cloud-gov-w3l1
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: cloud-gov-w3l1
        image: cloudgovweek3les2.azurecr.io/flasktestapp
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gov-w3l1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cloud-gov-w3l1