name: Build a Docker image and Push it to ACR

on: push
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: cloudgovweek3les2.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t cloudgovweek3les2.azurecr.io/flasktestapp:${{ github.sha }}
          docker push cloudgovweek3les2.azurecr.io/flasktestapp:${{ github.sha }}
      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: aksCluster1
          resource-group: SK-RP-W3L1

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: cloudgovweek3les2.azurecr.io
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: cloudgovsecret
      - uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            manifests/aksmanifest.yml
          images: |
            cloudgovweek3les2.azurecr.io/flasktestapp:${{ github.sha }}
          imagepullsecrets: |
            cloudgovsecret